CREATE TABLE FormResults (
	Result_ID INT NOT NULL PRIMARY KEY,
	LastName VARCHAR(30),
	FirstName VARCHAR(30),
	BirthDate DATE,
	Sex VARCHAR(6),
	ArrivalDate DATE,
	Arline VARCHAR(30),
	FlightNo INT,
	SeatNo INT,
	Address VARCHAR(30),
	City VARCHAR(30),
	State VARCHAR(2),
	Email VARCHAR(30),
	PhoneNo VARCHAR(30),
	Mobile BOOLEAN,
	Fever BOOLEAN,
	Cough BOOLEAN,
	Breathing BOOLEAN	
);
